### ISSUE TITLE
Add mkdoc ezlinks wikilink support

### ISSUE THREAD

**Issue by mofosyne** [mofosyne/mediawiki-to-markdown-python#2]
What i noticed is that in mkdocs ezlinks plugin support

I noticed when using mkdoc ezlinks plugin, it works, but only if all files are lowercase and spaces are `-` delimited.

I ended up using this command to fix the issue.

```
prename 'y/A-Z/a-z/; s/_/-/g' *
```

The nice thing about this is you can use `[[ ]]` notation still

FYI, this is the setting i used for my mkdocs

```
site_name: Designing Open Democracy
site_url: http://wiki.designingopendemocracy.com
theme: mkdocs
plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md
  - ezlinks:
      wikilinks: true
```
